/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.ufmt.biblioteca.Ui;

import br.ufmt.biblioteca.Ui.dto.AutorDTO;
import br.ufmt.biblioteca.service.AutorService;
import br.ufmt.biblioteca.service.Impl.AutorServiceImpl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class AutorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClienteJPanel
     */
    public AutorJPanel() {
        initComponents();
        atualizarTabela();
    }
    private void atualizarTabela() {
       AutorService service = new AutorServiceImpl();
        List<AutorDTO> lista = service.listar();
        
        DefaultTableModel dfm = (DefaultTableModel) tabelajTable.getModel();
        int linhas = dfm.getRowCount();
        for (int i = 0; i < linhas; i++) {
            dfm.removeRow(0);
        }
 
        
        for (AutorDTO  autorDTO  : lista) {
            Object[] linha = new Object[3];
            linha[0] = autorDTO.getId();
            linha[1] = autorDTO.getNome();
            linha[2] = autorDTO.getBiografia();
 
            
            dfm.addRow(linha);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IdJLabel = new javax.swing.JLabel();
        NomeJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idJTextField = new javax.swing.JTextField();
        nomejTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelajTable = new javax.swing.JTable();
        salvarjButton = new javax.swing.JButton();
        deletarjButton = new javax.swing.JButton();
        cancelarjButton = new javax.swing.JButton();
        editarjButton = new javax.swing.JButton();
        biografiajTextField = new javax.swing.JTextField();

        IdJLabel.setText("ID:");

        NomeJLabel.setText("Nome:");

        jLabel1.setText("Biografia:");

        idJTextField.setEditable(false);

        nomejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomejTextFieldActionPerformed(evt);
            }
        });

        tabelajTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Biografia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelajTable);

        salvarjButton.setText("Salvar");
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });

        deletarjButton.setText("Deletar");
        deletarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarjButtonActionPerformed(evt);
            }
        });

        cancelarjButton.setText("Cancelar");
        cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjButtonActionPerformed(evt);
            }
        });

        editarjButton.setText("Editar");
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(editarjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(biografiajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NomeJLabel)
                                    .addComponent(IdJLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salvarjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelarjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                        .addComponent(deletarjButton)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdJLabel))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(biografiajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarjButton)
                    .addComponent(deletarjButton)
                    .addComponent(cancelarjButton))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addComponent(editarjButton)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nomejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomejTextFieldActionPerformed

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // TODO add your handling code here:
        String id = idJTextField.getText();
        String nome = nomejTextField.getText();
        String biografia = biografiajTextField.getText();
        
        
        AutorDTO dto = new AutorDTO(id, nome, biografia);
        
        // enviando para a service
        AutorService service = new AutorServiceImpl();
        try {
            service.salvar(dto);
            JOptionPane.showMessageDialog(this, "Salvo com Sucesso!");
            cancelarjButtonActionPerformed(evt);
            atualizarTabela();
        } catch(Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        // TODO add your handling code here:
         idJTextField.setText("");
        nomejTextField.setText("");
        biografiajTextField.setText("");
       
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        // TODO add your handling code here:
        int total = tabelajTable.getSelectedRowCount();
        
        if(total != 1){
            JOptionPane.showMessageDialog(tabelajTable, "Por favor selecione somente uma linha para editar");
            return;
        }
        int linha = tabelajTable.getSelectedRow();
         String id = (String)tabelajTable.getValueAt(linha, 0);
         String nome = (String)tabelajTable.getValueAt(linha, 1);
         String biografia = (String)tabelajTable.getValueAt(linha, 2);
    
         
         idJTextField.setText(id);
         nomejTextField.setText(nome);
         biografiajTextField.setText(biografia);
     
    }//GEN-LAST:event_editarjButtonActionPerformed

    private void deletarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarjButtonActionPerformed
        // TODO add your handling code here:
        int total = tabelajTable.getSelectedRowCount();
        if(total <= 0){
            JOptionPane.showMessageDialog(tabelajTable, "Por favor selecione as linhas a serem enviadas");
            return;
        }
        try {
            int[] linhas = tabelajTable.getSelectedRows();
           AutorService service = new AutorServiceImpl();
            for(int linha: linhas) {
                String id = (String)tabelajTable.getValueAt(linha, 0);
                AutorDTO dto = new AutorDTO(id, null, null);
                service.remover(dto);
            }
            JOptionPane.showMessageDialog(tabelajTable, "Registro removidos com sucesso!");
            atualizarTabela();
        }catch (Exception erro){
             JOptionPane.showMessageDialog(tabelajTable, erro.getMessage());
        }
    }//GEN-LAST:event_deletarjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdJLabel;
    private javax.swing.JLabel NomeJLabel;
    private javax.swing.JTextField biografiajTextField;
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JButton deletarjButton;
    private javax.swing.JButton editarjButton;
    private javax.swing.JTextField idJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JTable tabelajTable;
    // End of variables declaration//GEN-END:variables
}
