/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.ufmt.biblioteca.Ui;

import br.ufmt.biblioteca.Ui.dto.EmprestimoDTO;
import br.ufmt.biblioteca.service.EmprestimoService;
import br.ufmt.biblioteca.service.Impl.EmprestimoServiceImpl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class EmprestimoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClienteJPanel
     */
    public EmprestimoJPanel() {
        initComponents();
        atualizarTabela();
    }
    private void atualizarTabela() {
        EmprestimoService service = new EmprestimoServiceImpl();
        List<EmprestimoDTO> lista = service.listar();
        
        DefaultTableModel dfm = (DefaultTableModel) tabelajTable.getModel();
        int linhas = dfm.getRowCount();
        for (int i = 0; i < linhas; i++) {
            dfm.removeRow(0);
        }
        
        for (EmprestimoDTO emprestimoDTO : lista) {
            Object[] linha = new Object[5];
            linha[0] = emprestimoDTO.getId();
            linha[1] = emprestimoDTO.getIdCliente();
            System.out.println(emprestimoDTO.getIdCliente());
            linha[2] = emprestimoDTO.getDataEmprestimo();
            linha[3] = emprestimoDTO.getDataDevolucao();
            linha[4] = emprestimoDTO.isDevolvido();
            
            dfm.addRow(linha);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IdJLabel = new javax.swing.JLabel();
        NomeJLabel = new javax.swing.JLabel();
        idJTextField = new javax.swing.JTextField();
        idClientejTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelajTable = new javax.swing.JTable();
        salvarjButton = new javax.swing.JButton();
        deletarjButton = new javax.swing.JButton();
        cancelarjButton = new javax.swing.JButton();
        editarjButton = new javax.swing.JButton();
        DevolvidojCheckBox = new javax.swing.JCheckBox();

        IdJLabel.setText("ID:");

        NomeJLabel.setText("Id do Cliente:");

        idJTextField.setEditable(false);

        idClientejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idClientejTextFieldActionPerformed(evt);
            }
        });

        tabelajTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Data do Emprestimo", "Data da devolução", "Devolvido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelajTable);

        salvarjButton.setText("Salvar");
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });

        deletarjButton.setText("Deletar");
        deletarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarjButtonActionPerformed(evt);
            }
        });

        cancelarjButton.setText("Cancelar");
        cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjButtonActionPerformed(evt);
            }
        });

        editarjButton.setText("Editar");
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });

        DevolvidojCheckBox.setText("Devolvido");
        DevolvidojCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevolvidojCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(editarjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DevolvidojCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IdJLabel)
                                .addGap(18, 18, 18)
                                .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NomeJLabel)
                                .addGap(7, 7, 7)
                                .addComponent(idClientejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salvarjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelarjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                        .addComponent(deletarjButton)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IdJLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomeJLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idClientejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(DevolvidojCheckBox)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarjButton)
                    .addComponent(deletarjButton)
                    .addComponent(cancelarjButton))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(editarjButton)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idClientejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idClientejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idClientejTextFieldActionPerformed

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // TODO add your handling code here:
        String id = idJTextField.getText();
        String idCliente = idClientejTextField.getText();
        boolean devolvido = DevolvidojCheckBox.isSelected();
     
        System.out.println(idCliente);
        EmprestimoDTO dto = new EmprestimoDTO(id, idCliente, null, null, devolvido);
        
        // enviando para a service
        EmprestimoService service = new EmprestimoServiceImpl();
        try {
            service.salvar(dto);
            JOptionPane.showMessageDialog(this, "Salvo com Sucesso!");
            cancelarjButtonActionPerformed(evt);
            atualizarTabela();
        } catch(Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        // TODO add your handling code here:
        idJTextField.setText("");
        idClientejTextField.setText("");
        DevolvidojCheckBox.setSelected(false);
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        // TODO add your handling code here:
        int total = tabelajTable.getSelectedRowCount();
        
        if(total != 1){
            JOptionPane.showMessageDialog(tabelajTable, "Por favor selecione somente uma linha para editar");
            return;
        }
        int linha = tabelajTable.getSelectedRow();
         String id = (String)tabelajTable.getValueAt(linha, 0);
         String nome = (String)tabelajTable.getValueAt(linha, 1);
         Boolean devolvido = (Boolean)tabelajTable.getValueAt(linha, 4);
      
         
         idJTextField.setText(id);
         idClientejTextField.setText(nome);
         DevolvidojCheckBox.setSelected(devolvido);
         
   
    }//GEN-LAST:event_editarjButtonActionPerformed

    private void deletarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarjButtonActionPerformed
        // TODO add your handling code here:
        int total = tabelajTable.getSelectedRowCount();
        if(total <= 0){
            JOptionPane.showMessageDialog(tabelajTable, "Por favor selecione as linhas a serem enviadas");
            return;
        }
        try {
            int[] linhas = tabelajTable.getSelectedRows();
            EmprestimoService service = new EmprestimoServiceImpl();
            for(int linha: linhas) {
                String id = (String)tabelajTable.getValueAt(linha, 0);
                EmprestimoDTO dto = new EmprestimoDTO(id, null, null, null, false);
                service.remover(dto);
            }
            JOptionPane.showMessageDialog(tabelajTable, "Registro removidos com sucesso!");
            atualizarTabela();
        }catch (Exception erro){
             JOptionPane.showMessageDialog(tabelajTable, erro.getMessage());
        }
    }//GEN-LAST:event_deletarjButtonActionPerformed

    private void DevolvidojCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevolvidojCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DevolvidojCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox DevolvidojCheckBox;
    private javax.swing.JLabel IdJLabel;
    private javax.swing.JLabel NomeJLabel;
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JButton deletarjButton;
    private javax.swing.JButton editarjButton;
    private javax.swing.JTextField idClientejTextField;
    private javax.swing.JTextField idJTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JTable tabelajTable;
    // End of variables declaration//GEN-END:variables
}
