/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ufmt.biblioteca.Ui;

/**
 *
 * @author Usuario
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conteudoJPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        clientesjMenuItem = new javax.swing.JMenuItem();
        autorjMenuItem = new javax.swing.JMenuItem();
        emprestimoMenuItem = new javax.swing.JMenuItem();
        LivrosjMenuItem = new javax.swing.JMenuItem();
        livrosEmprestadosjMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        conteudoJPanel.setLayout(new javax.swing.BoxLayout(conteudoJPanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Bem vindo ao sistema da biblioteca ");
        jLabel2.setToolTipText("ainda em desenvolvimento");
        conteudoJPanel.add(jLabel2);

        Menu.setText("Biblioteca");

        clientesjMenuItem.setText("Clientes");
        clientesjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesjMenuItemActionPerformed(evt);
            }
        });
        Menu.add(clientesjMenuItem);

        autorjMenuItem.setText("Autores");
        autorjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorjMenuItemActionPerformed(evt);
            }
        });
        Menu.add(autorjMenuItem);

        emprestimoMenuItem.setText("Emprestimos");
        emprestimoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestimoMenuItemActionPerformed(evt);
            }
        });
        Menu.add(emprestimoMenuItem);

        LivrosjMenuItem.setText("Livros");
        LivrosjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LivrosjMenuItemActionPerformed(evt);
            }
        });
        Menu.add(LivrosjMenuItem);

        livrosEmprestadosjMenuItem1.setText("Livros Emprestados");
        livrosEmprestadosjMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livrosEmprestadosjMenuItem1ActionPerformed(evt);
            }
        });
        Menu.add(livrosEmprestadosjMenuItem1);

        MenuBar.add(Menu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conteudoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conteudoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void autorjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorjMenuItemActionPerformed
        // TODO add your handling code here:
        conteudoJPanel.removeAll();
        conteudoJPanel.add(new AutorJPanel());
        conteudoJPanel.setVisible(false);
        conteudoJPanel.setVisible(true);
    }//GEN-LAST:event_autorjMenuItemActionPerformed

    private void clientesjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesjMenuItemActionPerformed
        // TODO add your handling code here:
        conteudoJPanel.removeAll();
        conteudoJPanel.add(new ClienteJPanel());
        conteudoJPanel.setVisible(false);
        conteudoJPanel.setVisible(true);
    }//GEN-LAST:event_clientesjMenuItemActionPerformed

    private void emprestimoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestimoMenuItemActionPerformed
        // TODO add your handling code here:
        conteudoJPanel.removeAll();
        conteudoJPanel.add(new EmprestimoJPanel());
        conteudoJPanel.setVisible(false);
        conteudoJPanel.setVisible(true);
    }//GEN-LAST:event_emprestimoMenuItemActionPerformed

    private void LivrosjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LivrosjMenuItemActionPerformed
        // TODO add your handling code here:
        conteudoJPanel.removeAll();
        conteudoJPanel.add(new LivrosJPanel());
        conteudoJPanel.setVisible(false);
        conteudoJPanel.setVisible(true);
    }//GEN-LAST:event_LivrosjMenuItemActionPerformed

    private void livrosEmprestadosjMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livrosEmprestadosjMenuItem1ActionPerformed
        // TODO add your handling code here:
        conteudoJPanel.removeAll();
        conteudoJPanel.add(new LivrosEmprestadosJPanel());
        conteudoJPanel.setVisible(false);
        conteudoJPanel.setVisible(true);
    }//GEN-LAST:event_livrosEmprestadosjMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LivrosjMenuItem;
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem autorjMenuItem;
    private javax.swing.JMenuItem clientesjMenuItem;
    private javax.swing.JPanel conteudoJPanel;
    private javax.swing.JMenuItem emprestimoMenuItem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem livrosEmprestadosjMenuItem1;
    // End of variables declaration//GEN-END:variables
}
