/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.ufmt.biblioteca.Ui;

import br.ufmt.biblioteca.Ui.dto.LivrosEmprestadosDTO;
import br.ufmt.biblioteca.service.Impl.LivrosEmprestadosServiceImpl;
import br.ufmt.biblioteca.service.LivrosEmprestadosService;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class LivrosEmprestadosJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClienteJPanel
     */
    public LivrosEmprestadosJPanel() {
        initComponents();
        atualizarTabela();
    }
    private void atualizarTabela() {
       LivrosEmprestadosService service = new LivrosEmprestadosServiceImpl();
        List<LivrosEmprestadosDTO> lista = service.listar();
        
        DefaultTableModel dfm = (DefaultTableModel) tabelajTable.getModel();
        int linhas = dfm.getRowCount();
        for (int i = 0; i < linhas; i++) {
            dfm.removeRow(0);
        }
 
        
        for (LivrosEmprestadosDTO  livrosEmprestadosDTO  : lista) {
            Object[] linha = new Object[2];
            linha[0] = livrosEmprestadosDTO.getIdEmprestimo();
            linha[1] = livrosEmprestadosDTO.getIdLivro();
           
 
            
            dfm.addRow(linha);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idEmprestimojTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelajTable = new javax.swing.JTable();
        salvarjButton = new javax.swing.JButton();
        deletarjButton = new javax.swing.JButton();
        cancelarjButton = new javax.swing.JButton();
        editarjButton = new javax.swing.JButton();
        idLivrojTextField = new javax.swing.JTextField();

        NomeJLabel.setText("Id Emprestimo:");

        jLabel1.setText("Id do livro:");

        idEmprestimojTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEmprestimojTextFieldActionPerformed(evt);
            }
        });

        tabelajTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID do Emprestimo", "Livro Emprestado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelajTable);

        salvarjButton.setText("Salvar");
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });

        deletarjButton.setText("Deletar");
        deletarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarjButtonActionPerformed(evt);
            }
        });

        cancelarjButton.setText("Cancelar");
        cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjButtonActionPerformed(evt);
            }
        });

        editarjButton.setText("Editar");
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(editarjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(salvarjButton)
                                .addGap(25, 25, 25)
                                .addComponent(cancelarjButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(idLivrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(NomeJLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(idEmprestimojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deletarjButton)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idEmprestimojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idLivrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarjButton)
                    .addComponent(deletarjButton)
                    .addComponent(cancelarjButton))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addComponent(editarjButton)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idEmprestimojTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEmprestimojTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idEmprestimojTextFieldActionPerformed

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // TODO add your handling code here:
        String idEmprestimo = idEmprestimojTextField.getText();
        String idLivro = idLivrojTextField.getText();
        
        
        LivrosEmprestadosDTO dto = new LivrosEmprestadosDTO(idEmprestimo, idLivro);
        
        // enviando para a service
        LivrosEmprestadosService service = new LivrosEmprestadosServiceImpl();
        try {
            service.salvar(dto);
            JOptionPane.showMessageDialog(this, "Salvo com Sucesso!");
            cancelarjButtonActionPerformed(evt);
            atualizarTabela();
        } catch(Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        // TODO add your handling code here:
 
        idEmprestimojTextField.setText("");
        idLivrojTextField.setText("");
       
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        // TODO add your handling code here:
        int total = tabelajTable.getSelectedRowCount();
        
        if(total != 1){
            JOptionPane.showMessageDialog(tabelajTable, "Por favor selecione somente uma linha para editar");
            return;
        }
        int linha = tabelajTable.getSelectedRow();
         String idEmpestimo = (String)tabelajTable.getValueAt(linha, 0);
         String idLivro = (String)tabelajTable.getValueAt(linha, 1);

         
         idEmprestimojTextField.setText(idEmpestimo);
         idLivrojTextField.setText(idLivro);
     
    }//GEN-LAST:event_editarjButtonActionPerformed

    private void deletarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarjButtonActionPerformed
        // TODO add your handling code here:
        int total = tabelajTable.getSelectedRowCount();
        if(total <= 0){
            JOptionPane.showMessageDialog(tabelajTable, "Por favor selecione as linhas a serem enviadas");
            return;
        }
        try {
            int[] linhas = tabelajTable.getSelectedRows();
            LivrosEmprestadosService service = new LivrosEmprestadosServiceImpl();
            for(int linha: linhas) {
                String idEmprestimo = (String)tabelajTable.getValueAt(linha, 0);
                 String idLivro = (String)tabelajTable.getValueAt(linha, 1);
                LivrosEmprestadosDTO dto = new LivrosEmprestadosDTO(idEmprestimo, idLivro);
                service.remover(dto);
            }
            JOptionPane.showMessageDialog(tabelajTable, "Registro removidos com sucesso!");
            atualizarTabela();
        }catch (Exception erro){
             JOptionPane.showMessageDialog(tabelajTable, erro.getMessage());
        }
    }//GEN-LAST:event_deletarjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NomeJLabel;
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JButton deletarjButton;
    private javax.swing.JButton editarjButton;
    private javax.swing.JTextField idEmprestimojTextField;
    private javax.swing.JTextField idLivrojTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JTable tabelajTable;
    // End of variables declaration//GEN-END:variables
}
