/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.ufmt.biblioteca.Ui;

import br.ufmt.biblioteca.Ui.dto.LivroDTO;
import br.ufmt.biblioteca.service.Impl.LivroServiceImpl;
import br.ufmt.biblioteca.service.LivroService;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class LivrosJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClienteJPanel
     */
    public LivrosJPanel() {
        initComponents();
        atualizarTabela();
    }
    private void atualizarTabela() {
        LivroService service = new LivroServiceImpl();
        List<LivroDTO> lista = service.listar();
        
        DefaultTableModel dfm = (DefaultTableModel) tabelajTable.getModel();
        int linhas = dfm.getRowCount();
        for (int i = 0; i < linhas; i++) {
            dfm.removeRow(0);
        }
        
        for (LivroDTO livroDTO : lista) {
            Object[] linha = new Object[5];
            linha[0] = livroDTO.getId();
            linha[1] = livroDTO.getTitulo();
            linha[2] = livroDTO.getIdAutor();
            linha[3] = livroDTO.getResumo();
            linha[4] = livroDTO.isDisponivel();
            
            dfm.addRow(linha);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IdJLabel = new javax.swing.JLabel();
        NomeJLabel = new javax.swing.JLabel();
        cpfJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idJTextField = new javax.swing.JTextField();
        nomejTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelajTable = new javax.swing.JTable();
        salvarjButton = new javax.swing.JButton();
        deletarjButton = new javax.swing.JButton();
        cancelarjButton = new javax.swing.JButton();
        editarjButton = new javax.swing.JButton();
        DevolvidojCheckBox = new javax.swing.JCheckBox();
        idAutorjTextField = new javax.swing.JTextField();
        resumojTextField1 = new javax.swing.JTextField();

        IdJLabel.setText("ID:");

        NomeJLabel.setText("Título:");

        cpfJLabel.setText("Autor:");

        jLabel1.setText("Resumo:");

        idJTextField.setEditable(false);

        nomejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomejTextFieldActionPerformed(evt);
            }
        });

        tabelajTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Título", "Autor", "Resumo", "Disponivel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelajTable);

        salvarjButton.setText("Salvar");
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });

        deletarjButton.setText("Deletar");
        deletarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarjButtonActionPerformed(evt);
            }
        });

        cancelarjButton.setText("Cancelar");
        cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjButtonActionPerformed(evt);
            }
        });

        editarjButton.setText("Editar");
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });

        DevolvidojCheckBox.setText("Disponivel");

        idAutorjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAutorjTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(editarjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(salvarjButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelarjButton)
                                .addGap(199, 199, 199))
                            .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deletarjButton)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resumojTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IdJLabel)
                                .addGap(18, 18, 18)
                                .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NomeJLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cpfJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idAutorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(DevolvidojCheckBox))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IdJLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomeJLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpfJLabel)
                    .addComponent(idAutorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(resumojTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(DevolvidojCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarjButton)
                    .addComponent(deletarjButton)
                    .addComponent(cancelarjButton))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editarjButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nomejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomejTextFieldActionPerformed

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // TODO add your handling code here:
        String id = idJTextField.getText();
        String nome = nomejTextField.getText();
        String idAutor = idAutorjTextField.getText();
        String resumo = resumojTextField1.getText();
        boolean devolvido = DevolvidojCheckBox.isSelected();
        
        LivroDTO dto = new LivroDTO(id, nome, idAutor, resumo, devolvido);
        
        // enviando para a service
       LivroService service = new LivroServiceImpl();
        try {
            service.salvar(dto);
            JOptionPane.showMessageDialog(this, "Salvo com Sucesso!");
            cancelarjButtonActionPerformed(evt);
            atualizarTabela();
        } catch(Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        // TODO add your handling code here:
         idJTextField.setText("");
        nomejTextField.setText("");
        idAutorjTextField.setText("");
        resumojTextField1.setText("");
        DevolvidojCheckBox.setSelected(false);
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        // TODO add your handling code here:
        int total = tabelajTable.getSelectedRowCount();
        
        if(total != 1){
            JOptionPane.showMessageDialog(tabelajTable, "Por favor selecione somente uma linha para editar");
            return;
        }
        int linha = tabelajTable.getSelectedRow();
         String id = (String)tabelajTable.getValueAt(linha, 0);
         String titulo = (String)tabelajTable.getValueAt(linha, 1);
         String idAutor = (String)tabelajTable.getValueAt(linha, 2);
         String resumo = (String)tabelajTable.getValueAt(linha, 3);
          Boolean devolvido = (Boolean)tabelajTable.getValueAt(linha, 4);
         
         idJTextField.setText(id);
         nomejTextField.setText(titulo);
         idAutorjTextField.setText(idAutor);
        resumojTextField1.setText(resumo);
        DevolvidojCheckBox.setSelected(devolvido);
    }//GEN-LAST:event_editarjButtonActionPerformed

    private void deletarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarjButtonActionPerformed
        // TODO add your handling code here:
        int total = tabelajTable.getSelectedRowCount();
        if(total <= 0){
            JOptionPane.showMessageDialog(tabelajTable, "Por favor selecione as linhas a serem enviadas");
            return;
        }
        try {
            int[] linhas = tabelajTable.getSelectedRows();
           LivroService service = new LivroServiceImpl();
            for(int linha: linhas) {
                String id = (String)tabelajTable.getValueAt(linha, 0);
                LivroDTO dto = new LivroDTO(id, null, null, null, false);
                service.remover(dto);
            }
            JOptionPane.showMessageDialog(tabelajTable, "Registro removidos com sucesso!");
            atualizarTabela();
        }catch (Exception erro){
             JOptionPane.showMessageDialog(tabelajTable, erro.getMessage());
        }
    }//GEN-LAST:event_deletarjButtonActionPerformed

    private void idAutorjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAutorjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idAutorjTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox DevolvidojCheckBox;
    private javax.swing.JLabel IdJLabel;
    private javax.swing.JLabel NomeJLabel;
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JLabel cpfJLabel;
    private javax.swing.JButton deletarjButton;
    private javax.swing.JButton editarjButton;
    private javax.swing.JTextField idAutorjTextField;
    private javax.swing.JTextField idJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JTextField resumojTextField1;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JTable tabelajTable;
    // End of variables declaration//GEN-END:variables
}
